### ISSUE TITLE
  # create a directory with scp

### ISSUE THREAD

**Issue by dineshPallapa** [net-ssh/net-scp#40]
I am trying create a directory in my remote location.

Is their any command equivalent in scp as sftp.
```
# create a directory
sftp.mkdir! "/path/to/directory"
```

Hope, Get some response. Thanks!

**Comment by 9mm** [comment]
scp.session.exec!('mkdir xyz')

**Comment by mfazekas** [comment]
Yep either use sftp or create dir with remote command, or just recursive copy and empty directory.
