### ISSUE TITLE
Slow thoughput problem

### ISSUE THREAD

**Issue by arthurzenika** [net-ssh/net-scp#46]
When using net-scp in the use case of https://github.com/test-kitchen/kitchen-ec2, I'm trying to upload 100MB to an AWS machine over a link that can upload this amount in a few minutes, it takes ages and trickles the data at very low rates. 

I've read https://stackoverflow.com/questions/4208603/performance-issues-with-ruby-and-netscp-transfers-sockets but I don't know if this is still a problem or if there is a fix.

**Comment by arthurlogilab** [comment]
Bump ? I'm going to have to find a way to ship my files using rsync or another channel... Am I the only one with this problem!?

**Comment by zrice57** [comment]
I've been experiencing the same issue. Between 2 EC2 instances a 1Gb file transfer hits about 1.5Mbps through net-scp. If I use the shell's scp command it hits > 400Mbps.

My use of this gem is wrapped by https://github.com/capistrano/sshkit . So I can easily resort to running shell `scp` commands for now.

**Comment by mfazekas** [comment]
To investigate need concrete versions (net-scp, net-ssh), and algs used. 

There were significant improvements if `ctr` was used for example:
https://github.com/net-ssh/net-ssh/pull/570

**Comment by mfazekas** [comment]
Closing issue as stale
