### ISSUE TITLE
Downgrade of net-scp after bundle update

### ISSUE THREAD

**Issue by rocket-turtle** [net-ssh/net-scp#52]
Hi folks,

last time we did `bundle update` it downgraded `net-scp`
- net-ssh: 5.2.2 (2019) -> 6.0.0 (April 20, 2020)
- net-scp: 2.0.0 (2019) -> 1.2.1 (2014)

We do not require thes gems but use `capistrano` which uses `net-scp` and `net-ssh`.

To fix this we had to require `gem 'net-scp', '~> 2.0'` directly.

Is there another way to do it or would it be possible to release Version 3 for net-scp?

Thank you in advance.

**Comment by mfazekas** [comment]
@rocket-turtle yep we have net-scp 3.0.rc1 fixing that we should release it

**Comment by fzipi** [comment]
With net-ssh 6.0.2 I guess now this may be the next release...

**Comment by mfazekas** [comment]
https://rubygems.org/gems/net-scp/versions/3.0.0

**Comment by rocket-turtle** [comment]
Thank you, really appreciate your work.
