### ISSUE TITLE
Bug: add support for net-ssh 7 (unexpected downgrade from net-scp 3 to 1.2.1)

### ISSUE THREAD

**Issue by collimarco** [net-ssh/net-scp#61]
Hello,

net-ssh has released version 7.

In the `.gemspec` of this gem there is this line:

```
spec.add_runtime_dependency(%q<net-ssh>, [">= 2.6.5", "< 7.0.0"])
```

Please remove that `< 7.0.0` otherwise you get a disastrous downgrade of this gem:

```
Fetching net-ssh 7.0.1 (was 6.1.0)
Installing net-ssh 7.0.1 (was 6.1.0)
Fetching net-scp 1.2.1 (was 3.0.0)
Installing net-scp 1.2.1 (was 3.0.0)
```

**Comment by Westacular** [comment]
Is there a plan to release a version bump of net-scp itself soon containing this fix?

Because this issue will continue to exist and affect people until there's a new _published_ version of net-scp with the `net-ssh < 8.0.0` change.
