### ISSUE TITLE
recursive issue

### ISSUE THREAD

**Issue by 4zv4l** [net-ssh/net-scp#68]
in the doc it is written
`:recursive - the local parameter refers to a local directory, which should be uploaded to a new directory named remote on the remote server.`

Wouldn't it better to copy the `local dir` to `remote dir` ?
Because now if I upload a directory `local/mine` to `remote/test`, it will upload it to `remote/test/mine`.
Or what I wanted to do was `remote/test` to be the same as `local/mine` because otherwise I need to make a symlink
`remote/test` = `remote/mine` and use the function with `local/mine` to `remote` to finally get `remote/test` to contain the file from `local/mine`.
Sounds confusing, hope it is clear xD

**Comment by mfazekas** [comment]
@4zv4l sorry this is the way scp works.
